# Generated by Django 4.2.3 on 2023-07-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverpage',
            field=models.FileField(upload_to='media/coverpage/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
