# Generated by Django 4.2.3 on 2023-08-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
